title: "jxst.me"
description: "Systems. Layers. Experiments."
url: "https://jxst.me"

markdown: kramdown
theme: minima

# Let Jekyll show future-dated posts
future: true

# Make sure posts output correctly
collections:
  posts:
    output: true

# Permalink structure for nice blog URLs
permalink: /blog/:title/
